"""Initial schema: companies, roles, users, customers, tickets

Written from app.models rather than autogenerated, so it can be applied to an
empty database without first having one to diff against.

Revision ID: 0001_initial
Revises:
"""

from alembic import op
import sqlalchemy as sa

from app.db.types import UtcDateTime, utcnow

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column("created_at", UtcDateTime(), server_default=utcnow(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=True),
    ]


def upgrade() -> None:
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Unicode(50), nullable=False),
        sa.Column("email", sa.Unicode(50), nullable=True),
        sa.Column("phone", sa.Unicode(13), nullable=True),
        sa.Column("is_active", sa.Boolean(),
                  server_default=sa.sql.expression.true(), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Unicode(50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.Unicode(50), nullable=False),
        sa.Column("email", sa.Unicode(50), nullable=False),
        sa.Column("password_hash", sa.Unicode(255), nullable=False),
        sa.Column("is_active", sa.Boolean(),
                  server_default=sa.sql.expression.true(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.Unicode(200), nullable=False),
        sa.Column("phone", sa.Unicode(50), nullable=False),
        sa.Column("email", sa.Unicode(320), nullable=True),
        sa.Column("is_active", sa.Boolean(),
                  server_default=sa.sql.expression.true(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("assigned_agent_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.Unicode(200), nullable=False),
        sa.Column("description", sa.UnicodeText(), nullable=True),
        sa.Column("procedure_steps", sa.UnicodeText(), nullable=True),
        sa.Column("status", sa.Unicode(50),
                  server_default=sa.text("'pending_follow_up'"), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(["assigned_agent_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # The application assumes these roles exist; create_super_admin.py fails
    # without them.
    op.bulk_insert(
        sa.table("roles", sa.column("name", sa.Unicode)),
        [{"name": "super_admin"}, {"name": "admin"}, {"name": "agent"}],
    )


def downgrade() -> None:
    op.drop_table("tickets")
    op.drop_table("customers")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("companies")
